suppressWarnings(suppressMessages(library(shiny, quietly = T, warn.conflicts = F)))
# source("app.R")
setwd("C:/Users/Zach/Documents/NYCEM/NYCEM-Weather-Dashboard")
source("server.R")
source("ui.R")
cat("To access the dashboard, copy and paste the URL below in a browser")
runApp(".")